inherit_gem:
  gnar-style:
    - "rubocop/rubocop.yml"

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Max: 120
  Severity: refactor

Style/StringLiterals:
  EnforcedStyle: single_quotes
