name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.0, 3.1, 3.2]

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Delete lockfile (to make sure it works with gem install)
        run: rm Gemfile.lock

      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec ruby ./test/test.rb

      - name: Lint code
        run: bundle exec rubocop

      - name: Audit code
        run: bundle exec bundler-audit check --update
